# Tested using AWS CodeBuild
version: 0.2

phases:
  install:
    commands:
   
  build:
    commands:
    commands: 
      - TARGET_ENV="${BUILD_ENV:-uat}"
      - echo "TARGET_ENV : $TARGET_ENV "    
